spring:
  application:
    name: SpringLab

#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.129.49:3306/TEST?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      schema-locations: classpath:db/schema-h2.sql
#      data-locations: classpath:db/data-h2.sql